package com.monstrous.utils;

import com.monstrous.webgpu.WebGPU_JNI;
import jnr.ffi.LibraryLoader;
import jnr.ffi.Runtime;
import jnr.ffi.Pointer;

import java.nio.ByteBuffer;

public class WgpuJava {

    /**
     * The function bindings generated by jnr-ffi
     */
    private static Runtime runtime;
    private static WebGPUUtils_JNI utils;

    public static WebGPU_JNI init(){

        WebGPU_JNI webGPU = LibraryLoader.create(WebGPU_JNI.class).load("dawn"); // load the library
        utils = LibraryLoader.create(WebGPUUtils_JNI.class).load("webgpuUtils"); // load the library
        runtime = Runtime.getRuntime(webGPU);
        return webGPU;
    }

    // todo Some nicer API?
    public static WebGPUUtils_JNI getUtils(){
        return utils;
    }




    /**
     * Sets the log level for the Rust wgpu library.
     * @param level the minimum level to log
     */
//    public static void setWgpuLogLevel(WgpuLogLevel level){
//        wgpuNative.wgpu_set_log_level(level);
//    }

    /**
     * returns a string of the Wgpu-native library version in the format
     * "major.minor.patch"
     */
//    public static String getWgpuNativeVersion(){
//        int version = wgpuNative.wgpu_get_version();
//        int major = (version >> 16) & 0xFF;
//        int minor = (version >> 8) & 0xFF;
//        int patch = version & 0xff;
//
//        return String.format("%d.%d.%d", major, minor, patch);
//    }

    /**
     * Wraps a series of long values in a pointer in direct memory.
     */
    public static Pointer createLongArrayPointer(long[] longs){
        Pointer ptr = WgpuJava.createDirectPointer(longs.length * Long.BYTES);

        for(int i = 0; i < longs.length; i++){
            ptr.putLongLong(i * Long.BYTES, longs[i]);
        }

        return ptr;
    }

    /**
     * Wraps a series of integer values in a pointer in direct memory.
     */
    public static Pointer createIntegerArrayPointer(int[] ints){
        Pointer ptr = WgpuJava.createDirectPointer(ints.length * Integer.BYTES);

        for(int i = 0; i < ints.length; i++){
            ptr.putInt(i * Integer.BYTES, ints[i]);
        }

        return ptr;
    }

    /**
     * Wraps a series of float values in a pointer in direct memory.
     */
    public static Pointer createFloatArrayPointer(float[] floats){
        Pointer ptr = WgpuJava.createDirectPointer(floats.length * Float.BYTES);

        for(int i = 0; i < floats.length; i++){
            ptr.putFloat(i * Float.BYTES, floats[i]);   // MM said Integer
        }

        return ptr;
    }

    /**
     * Copies the given data into a DirectByteBuffer and
     * then returns the buffer's pointer
     *
     * @see ByteBuffer#allocateDirect(int)
     */
    public static Pointer createByteArrayPointer(byte[] bytes){
        var dataBuffer = ByteBuffer.allocateDirect(bytes.length).put(bytes);
        dataBuffer.rewind();

        return WgpuJava.createByteBufferPointer(dataBuffer);
    }

    /**
     * returns a null pointer
     */
    public static Pointer createNullPointer(){
        return Pointer.wrap(runtime, 0x00);
    }

    /**
     * returns the pointer to the provided byte buffer.
     *
     * @throws IllegalArgumentException if buffer isn't using direct memory, or buffer.position != 0
     */
    public static Pointer createByteBufferPointer(ByteBuffer buffer) {
        if(!buffer.isDirect()){
            throw new IllegalArgumentException("Buffer must be direct!");
        }

        if(buffer.position() > 0){
            throw new IllegalArgumentException("Buffer should have a position of zero!");
        }

        return Pointer.wrap(runtime, buffer);
    }

    /**
     * a pointer in direct memory with the given size
     *
     * @param size (in bytes) space allocated for the pointer
     */
    public static Pointer createDirectPointer(int size) {
        return runtime.getMemoryManager().allocateDirect(size);
    }

    /**
     * Used for unit testing only!
     */
    public static void setRuntime(Runtime runtime) {
        WgpuJava.runtime = runtime;
    }

    public static Runtime getRuntime() {
        return runtime;
    }
}
