package com.monstrous.webgpu;

import com.monstrous.utils.JavaWebGPU;
import com.monstrous.utils.CStrPointer;
import com.monstrous.utils.WgpuJavaStruct;
import com.monstrous.utils.RustCString;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPURenderPassTimestampWrites extends WgpuJavaStruct {

    private final Struct.Pointer querySet = new Struct.Pointer();
    private final Struct.Unsigned32 beginningOfPassWriteIndex = new Struct.Unsigned32();
    private final Struct.Unsigned32 endOfPassWriteIndex = new Struct.Unsigned32();

    private WGPURenderPassTimestampWrites(){}

    @Deprecated
    public WGPURenderPassTimestampWrites(Runtime runtime){
        super(runtime);
    }

	/**
	* Creates this struct on the java heap.
	* In general, this should <b>not</b> be used because these structs
	* cannot be directly passed into native code. 
	*/
    public static WGPURenderPassTimestampWrites createHeap(){
        return new WGPURenderPassTimestampWrites();
    }

	/**
	* Creates this struct in direct memory.
	* This is how most structs should be created (unless, they
	* are members of a nothing struct)
	* 
	* @see WgpuJavaStruct#useDirectMemory
	*/
    public static WGPURenderPassTimestampWrites createDirect(){
        WGPURenderPassTimestampWrites struct = new WGPURenderPassTimestampWrites();
        struct.useDirectMemory();
        return struct;
    }


    public jnr.ffi.Pointer getQuerySet(){
        return querySet.get();
    }

    public void setQuerySet(jnr.ffi.Pointer x){
        this.querySet.set(x);
    }

    public long getBeginningOfPassWriteIndex(){
        return beginningOfPassWriteIndex.get();
    }

    public void setBeginningOfPassWriteIndex(long x){
        this.beginningOfPassWriteIndex.set(x);
    }

    public long getEndOfPassWriteIndex(){
        return endOfPassWriteIndex.get();
    }

    public void setEndOfPassWriteIndex(long x){
        this.endOfPassWriteIndex.set(x);
    }

}