package com.monstrous.webgpu;

import com.monstrous.utils.JavaWebGPU;
import com.monstrous.utils.CStrPointer;
import com.monstrous.utils.WgpuJavaStruct;
import com.monstrous.utils.RustCString;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUFragmentState extends WgpuJavaStruct {

    private final DynamicStructRef<WGPUChainedStruct> nextInChain = new DynamicStructRef<>(WGPUChainedStruct.class);
    private final Struct.Pointer module = new Struct.Pointer();
    private final @CStrPointer Struct.Pointer entryPoint = new Struct.Pointer();
    private final Struct.size_t constantCount = new Struct.size_t();
    private final DynamicStructRef<WGPUConstantEntry> constants = new DynamicStructRef<>(WGPUConstantEntry.class);
    private final Struct.size_t targetCount = new Struct.size_t();
    private final DynamicStructRef<WGPUColorTargetState> targets = new DynamicStructRef<>(WGPUColorTargetState.class);

    private WGPUFragmentState(){}

    @Deprecated
    public WGPUFragmentState(Runtime runtime){
        super(runtime);
    }

	/**
	* Creates this struct on the java heap.
	* In general, this should <b>not</b> be used because these structs
	* cannot be directly passed into native code. 
	*/
    public static WGPUFragmentState createHeap(){
        return new WGPUFragmentState();
    }

	/**
	* Creates this struct in direct memory.
	* This is how most structs should be created (unless, they
	* are members of a nothing struct)
	* 
	* @see WgpuJavaStruct#useDirectMemory
	*/
    public static WGPUFragmentState createDirect(){
        WGPUFragmentState struct = new WGPUFragmentState();
        struct.useDirectMemory();
        return struct;
    }


    public DynamicStructRef<WGPUChainedStruct> getNextInChain(){
        return nextInChain;
    }

    public void setNextInChain(WGPUChainedStruct... x){
        if(x.length == 0 || x[0] == null){
            this.nextInChain.set(JavaWebGPU.createNullPointer());
        } else {
            this.nextInChain.set(x);
        }
    }

    public jnr.ffi.Pointer getModule(){
        return module.get();
    }

    public void setModule(jnr.ffi.Pointer x){
        this.module.set(x);
    }

    public java.lang.String getEntryPoint(){
        return RustCString.fromPointer(entryPoint.get());
    }

    public void setEntryPoint(java.lang.String x){
        this.entryPoint.set(RustCString.toPointer(x));
    }

    public long getConstantCount(){
        return constantCount.get();
    }

    public void setConstantCount(long x){
        this.constantCount.set(x);
    }

    public DynamicStructRef<WGPUConstantEntry> getConstants(){
        return constants;
    }

    public void setConstants(WGPUConstantEntry... x){
        if(x.length == 0 || x[0] == null){
            this.constants.set(JavaWebGPU.createNullPointer());
        } else {
            this.constants.set(x);
        }
    }

    public long getTargetCount(){
        return targetCount.get();
    }

    public void setTargetCount(long x){
        this.targetCount.set(x);
    }

    public DynamicStructRef<WGPUColorTargetState> getTargets(){
        return targets;
    }

    public void setTargets(WGPUColorTargetState... x){
        if(x.length == 0 || x[0] == null){
            this.targets.set(JavaWebGPU.createNullPointer());
        } else {
            this.targets.set(x);
        }
    }

}