package com.monstrous.webgpu;

import com.monstrous.utils.JavaWebGPU;
import com.monstrous.utils.CStrPointer;
import com.monstrous.utils.WgpuJavaStruct;
import com.monstrous.utils.RustCString;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUPrimitiveState extends WgpuJavaStruct {

    private final DynamicStructRef<WGPUChainedStruct> nextInChain = new DynamicStructRef<>(WGPUChainedStruct.class);
    private final Struct.Enum<WGPUPrimitiveTopology> topology = new Struct.Enum<>(WGPUPrimitiveTopology.class);
    private final Struct.Enum<WGPUIndexFormat> stripIndexFormat = new Struct.Enum<>(WGPUIndexFormat.class);
    private final Struct.Enum<WGPUFrontFace> frontFace = new Struct.Enum<>(WGPUFrontFace.class);
    private final Struct.Enum<WGPUCullMode> cullMode = new Struct.Enum<>(WGPUCullMode.class);

    private WGPUPrimitiveState(){}

    @Deprecated
    public WGPUPrimitiveState(Runtime runtime){
        super(runtime);
    }

	/**
	* Creates this struct on the java heap.
	* In general, this should <b>not</b> be used because these structs
	* cannot be directly passed into native code. 
	*/
    public static WGPUPrimitiveState createHeap(){
        return new WGPUPrimitiveState();
    }

	/**
	* Creates this struct in direct memory.
	* This is how most structs should be created (unless, they
	* are members of a nothing struct)
	* 
	* @see WgpuJavaStruct#useDirectMemory
	*/
    public static WGPUPrimitiveState createDirect(){
        WGPUPrimitiveState struct = new WGPUPrimitiveState();
        struct.useDirectMemory();
        return struct;
    }


    public DynamicStructRef<WGPUChainedStruct> getNextInChain(){
        return nextInChain;
    }

    public void setNextInChain(WGPUChainedStruct... x){
        if(x.length == 0 || x[0] == null){
            this.nextInChain.set(JavaWebGPU.createNullPointer());
        } else {
            this.nextInChain.set(x);
        }
    }

    public WGPUPrimitiveTopology getTopology(){
        return topology.get();
    }

    public void setTopology(WGPUPrimitiveTopology x){
        this.topology.set(x);
    }

    public WGPUIndexFormat getStripIndexFormat(){
        return stripIndexFormat.get();
    }

    public void setStripIndexFormat(WGPUIndexFormat x){
        this.stripIndexFormat.set(x);
    }

    public WGPUFrontFace getFrontFace(){
        return frontFace.get();
    }

    public void setFrontFace(WGPUFrontFace x){
        this.frontFace.set(x);
    }

    public WGPUCullMode getCullMode(){
        return cullMode.get();
    }

    public void setCullMode(WGPUCullMode x){
        this.cullMode.set(x);
    }

}