package com.monstrous.webgpu;

import com.monstrous.utils.JavaWebGPU;
import com.monstrous.utils.CStrPointer;
import com.monstrous.utils.WgpuJavaStruct;
import com.monstrous.utils.RustCString;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUDawnComputePipelineFullSubgroups extends WgpuJavaStruct {

    private final WGPUChainedStruct chain = inner(WGPUChainedStruct.createHeap());
    private final Struct.Unsigned32 requiresFullSubgroups = new Struct.Unsigned32();

    private WGPUDawnComputePipelineFullSubgroups(){}

    @Deprecated
    public WGPUDawnComputePipelineFullSubgroups(Runtime runtime){
        super(runtime);
    }

	/**
	* Creates this struct on the java heap.
	* In general, this should <b>not</b> be used because these structs
	* cannot be directly passed into native code. 
	*/
    public static WGPUDawnComputePipelineFullSubgroups createHeap(){
        return new WGPUDawnComputePipelineFullSubgroups();
    }

	/**
	* Creates this struct in direct memory.
	* This is how most structs should be created (unless, they
	* are members of a nothing struct)
	* 
	* @see WgpuJavaStruct#useDirectMemory
	*/
    public static WGPUDawnComputePipelineFullSubgroups createDirect(){
        WGPUDawnComputePipelineFullSubgroups struct = new WGPUDawnComputePipelineFullSubgroups();
        struct.useDirectMemory();
        return struct;
    }


    public WGPUChainedStruct getChain(){
        return chain;
    }

    public long getRequiresFullSubgroups(){
        return requiresFullSubgroups.get();
    }

    public void setRequiresFullSubgroups(long x){
        this.requiresFullSubgroups.set(x);
    }

}