package com.monstrous.webgpu;


/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public enum WGPUWaitStatus {
    Success,
    TimedOut,
    UnsupportedTimeout,
    UnsupportedCount,
    UnsupportedMixedSources,
    Unknown,
}