package com.monstrous.webgpu;

import com.monstrous.utils.JavaWebGPU;
import com.monstrous.utils.CStrPointer;
import com.monstrous.utils.WgpuJavaStruct;
import com.monstrous.utils.RustCString;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUSharedTextureMemoryVkDedicatedAllocationDescriptor extends WgpuJavaStruct {

    private final WGPUChainedStruct chain = inner(WGPUChainedStruct.createHeap());
    private final Struct.Unsigned32 dedicatedAllocation = new Struct.Unsigned32();

    private WGPUSharedTextureMemoryVkDedicatedAllocationDescriptor(){}

    @Deprecated
    public WGPUSharedTextureMemoryVkDedicatedAllocationDescriptor(Runtime runtime){
        super(runtime);
    }

	/**
	* Creates this struct on the java heap.
	* In general, this should <b>not</b> be used because these structs
	* cannot be directly passed into native code. 
	*/
    public static WGPUSharedTextureMemoryVkDedicatedAllocationDescriptor createHeap(){
        return new WGPUSharedTextureMemoryVkDedicatedAllocationDescriptor();
    }

	/**
	* Creates this struct in direct memory.
	* This is how most structs should be created (unless, they
	* are members of a nothing struct)
	* 
	* @see WgpuJavaStruct#useDirectMemory
	*/
    public static WGPUSharedTextureMemoryVkDedicatedAllocationDescriptor createDirect(){
        WGPUSharedTextureMemoryVkDedicatedAllocationDescriptor struct = new WGPUSharedTextureMemoryVkDedicatedAllocationDescriptor();
        struct.useDirectMemory();
        return struct;
    }


    public WGPUChainedStruct getChain(){
        return chain;
    }

    public long getDedicatedAllocation(){
        return dedicatedAllocation.get();
    }

    public void setDedicatedAllocation(long x){
        this.dedicatedAllocation.set(x);
    }

}