package com.monstrous.webgpu;

import com.monstrous.utils.JavaWebGPU;
import com.monstrous.utils.CStrPointer;
import com.monstrous.utils.WgpuJavaStruct;
import com.monstrous.utils.RustCString;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUDawnWireWGSLControl extends WgpuJavaStruct {

    private final WGPUChainedStruct chain = inner(WGPUChainedStruct.createHeap());
    private final Struct.Unsigned32 enableExperimental = new Struct.Unsigned32();
    private final Struct.Unsigned32 enableUnsafe = new Struct.Unsigned32();
    private final Struct.Unsigned32 enableTesting = new Struct.Unsigned32();

    private WGPUDawnWireWGSLControl(){}

    @Deprecated
    public WGPUDawnWireWGSLControl(Runtime runtime){
        super(runtime);
    }

	/**
	* Creates this struct on the java heap.
	* In general, this should <b>not</b> be used because these structs
	* cannot be directly passed into native code. 
	*/
    public static WGPUDawnWireWGSLControl createHeap(){
        return new WGPUDawnWireWGSLControl();
    }

	/**
	* Creates this struct in direct memory.
	* This is how most structs should be created (unless, they
	* are members of a nothing struct)
	* 
	* @see WgpuJavaStruct#useDirectMemory
	*/
    public static WGPUDawnWireWGSLControl createDirect(){
        WGPUDawnWireWGSLControl struct = new WGPUDawnWireWGSLControl();
        struct.useDirectMemory();
        return struct;
    }


    public WGPUChainedStruct getChain(){
        return chain;
    }

    public long getEnableExperimental(){
        return enableExperimental.get();
    }

    public void setEnableExperimental(long x){
        this.enableExperimental.set(x);
    }

    public long getEnableUnsafe(){
        return enableUnsafe.get();
    }

    public void setEnableUnsafe(long x){
        this.enableUnsafe.set(x);
    }

    public long getEnableTesting(){
        return enableTesting.get();
    }

    public void setEnableTesting(long x){
        this.enableTesting.set(x);
    }

}