package com.monstrous.webgpu;

import com.monstrous.utils.JavaWebGPU;
import com.monstrous.utils.CStrPointer;
import com.monstrous.utils.WgpuJavaStruct;
import com.monstrous.utils.RustCString;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUStencilFaceState extends WgpuJavaStruct {

    private final Struct.Enum<WGPUCompareFunction> compare = new Struct.Enum<>(WGPUCompareFunction.class);
    private final Struct.Enum<WGPUStencilOperation> failOp = new Struct.Enum<>(WGPUStencilOperation.class);
    private final Struct.Enum<WGPUStencilOperation> depthFailOp = new Struct.Enum<>(WGPUStencilOperation.class);
    private final Struct.Enum<WGPUStencilOperation> passOp = new Struct.Enum<>(WGPUStencilOperation.class);

    private WGPUStencilFaceState(){}

    @Deprecated
    public WGPUStencilFaceState(Runtime runtime){
        super(runtime);
    }

	/**
	* Creates this struct on the java heap.
	* In general, this should <b>not</b> be used because these structs
	* cannot be directly passed into native code. 
	*/
    public static WGPUStencilFaceState createHeap(){
        return new WGPUStencilFaceState();
    }

	/**
	* Creates this struct in direct memory.
	* This is how most structs should be created (unless, they
	* are members of a nothing struct)
	* 
	* @see WgpuJavaStruct#useDirectMemory
	*/
    public static WGPUStencilFaceState createDirect(){
        WGPUStencilFaceState struct = new WGPUStencilFaceState();
        struct.useDirectMemory();
        return struct;
    }


    public WGPUCompareFunction getCompare(){
        return compare.get();
    }

    public void setCompare(WGPUCompareFunction x){
        this.compare.set(x);
    }

    public WGPUStencilOperation getFailOp(){
        return failOp.get();
    }

    public void setFailOp(WGPUStencilOperation x){
        this.failOp.set(x);
    }

    public WGPUStencilOperation getDepthFailOp(){
        return depthFailOp.get();
    }

    public void setDepthFailOp(WGPUStencilOperation x){
        this.depthFailOp.set(x);
    }

    public WGPUStencilOperation getPassOp(){
        return passOp.get();
    }

    public void setPassOp(WGPUStencilOperation x){
        this.passOp.set(x);
    }

}