package com.monstrous.webgpu;

import com.monstrous.utils.CStrPointer;
import com.monstrous.utils.WgpuJavaStruct;
import com.monstrous.utils.RustCString;
import jnr.ffi.Runtime;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUDawnCacheDeviceDescriptor extends WgpuJavaStruct {

    private final WGPUChainedStruct chain = inner(WGPUChainedStruct.createHeap());
    private final @CStrPointer Pointer isolationKey = new Pointer();
    private final Pointer loadDataFunction = new Pointer();
    private final Pointer storeDataFunction = new Pointer();
    private final Pointer functionUserdata = new Pointer();

    private WGPUDawnCacheDeviceDescriptor(){}

    @Deprecated
    public WGPUDawnCacheDeviceDescriptor(Runtime runtime){
        super(runtime);
    }

	/**
	* Creates this struct on the java heap.
	* In general, this should <b>not</b> be used because these structs
	* cannot be directly passed into native code. 
	*/
    public static WGPUDawnCacheDeviceDescriptor createHeap(){
        return new WGPUDawnCacheDeviceDescriptor();
    }

	/**
	* Creates this struct in direct memory.
	* This is how most structs should be created (unless, they
	* are members of a nothing struct)
	* 
	* @see WgpuJavaStruct#useDirectMemory
	*/
    public static WGPUDawnCacheDeviceDescriptor createDirect(){
        var struct = new WGPUDawnCacheDeviceDescriptor();
        struct.useDirectMemory();
        return struct;
    }


    public WGPUChainedStruct getChain(){
        return chain;
    }

    public java.lang.String getIsolationKey(){
        return RustCString.fromPointer(isolationKey.get());
    }

    public void setIsolationKey(java.lang.String x){
        this.isolationKey.set(RustCString.toPointer(x));
    }

    public jnr.ffi.Pointer getLoadDataFunction(){
        return loadDataFunction.get();
    }

    public void setLoadDataFunction(jnr.ffi.Pointer x){
        this.loadDataFunction.set(x);
    }

    public jnr.ffi.Pointer getStoreDataFunction(){
        return storeDataFunction.get();
    }

    public void setStoreDataFunction(jnr.ffi.Pointer x){
        this.storeDataFunction.set(x);
    }

    public jnr.ffi.Pointer getFunctionUserdata(){
        return functionUserdata.get();
    }

    public void setFunctionUserdata(jnr.ffi.Pointer x){
        this.functionUserdata.set(x);
    }

}