package com.monstrous.webgpu;

import com.monstrous.utils.JavaWebGPU;
import com.monstrous.utils.CStrPointer;
import com.monstrous.utils.WgpuJavaStruct;
import com.monstrous.utils.RustCString;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUSharedTextureMemoryVkImageLayoutBeginState extends WgpuJavaStruct {

    private final WGPUChainedStruct chain = inner(WGPUChainedStruct.createHeap());
    private final Struct.Signed32 oldLayout = new Struct.Signed32();
    private final Struct.Signed32 newLayout = new Struct.Signed32();

    private WGPUSharedTextureMemoryVkImageLayoutBeginState(){}

    @Deprecated
    public WGPUSharedTextureMemoryVkImageLayoutBeginState(Runtime runtime){
        super(runtime);
    }

	/**
	* Creates this struct on the java heap.
	* In general, this should <b>not</b> be used because these structs
	* cannot be directly passed into native code. 
	*/
    public static WGPUSharedTextureMemoryVkImageLayoutBeginState createHeap(){
        return new WGPUSharedTextureMemoryVkImageLayoutBeginState();
    }

	/**
	* Creates this struct in direct memory.
	* This is how most structs should be created (unless, they
	* are members of a nothing struct)
	* 
	* @see WgpuJavaStruct#useDirectMemory
	*/
    public static WGPUSharedTextureMemoryVkImageLayoutBeginState createDirect(){
        WGPUSharedTextureMemoryVkImageLayoutBeginState struct = new WGPUSharedTextureMemoryVkImageLayoutBeginState();
        struct.useDirectMemory();
        return struct;
    }


    public WGPUChainedStruct getChain(){
        return chain;
    }

    public int getOldLayout(){
        return oldLayout.get();
    }

    public void setOldLayout(int x){
        this.oldLayout.set(x);
    }

    public int getNewLayout(){
        return newLayout.get();
    }

    public void setNewLayout(int x){
        this.newLayout.set(x);
    }

}