package com.monstrous.webgpu;

import com.monstrous.utils.WgpuJava;
import com.monstrous.utils.CStrPointer;
import com.monstrous.utils.WgpuJavaStruct;
import com.monstrous.utils.RustCString;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUDrmFormatProperties extends WgpuJavaStruct {

    private final Unsigned64 modifier = new Unsigned64();
    private final Unsigned32 modifierPlaneCount = new Unsigned32();

    private WGPUDrmFormatProperties(){}

    @Deprecated
    public WGPUDrmFormatProperties(Runtime runtime){
        super(runtime);
    }

	/**
	* Creates this struct on the java heap.
	* In general, this should <b>not</b> be used because these structs
	* cannot be directly passed into native code. 
	*/
    public static WGPUDrmFormatProperties createHeap(){
        return new WGPUDrmFormatProperties();
    }

	/**
	* Creates this struct in direct memory.
	* This is how most structs should be created (unless, they
	* are members of a nothing struct)
	* 
	* @see WgpuJavaStruct#useDirectMemory
	*/
    public static WGPUDrmFormatProperties createDirect(){
        var struct = new WGPUDrmFormatProperties();
        struct.useDirectMemory();
        return struct;
    }


    public @jnr.ffi.types.u_int64_t long getModifier(){
        return modifier.get();
    }

    public void setModifier(@jnr.ffi.types.u_int64_t long x){
        this.modifier.set(x);
    }

    public long getModifierPlaneCount(){
        return modifierPlaneCount.get();
    }

    public void setModifierPlaneCount(long x){
        this.modifierPlaneCount.set(x);
    }

}