package com.monstrous.webgpu;

import com.monstrous.utils.WgpuJavaStruct;
import jnr.ffi.Runtime;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUYCbCrVkDescriptor extends WgpuJavaStruct {

    private final WGPUChainedStruct chain = inner(WGPUChainedStruct.createHeap());
    private final Unsigned32 vkFormat = new Unsigned32();
    private final Unsigned32 vkYCbCrModel = new Unsigned32();
    private final Unsigned32 vkYCbCrRange = new Unsigned32();
    private final Unsigned32 vkComponentSwizzleRed = new Unsigned32();
    private final Unsigned32 vkComponentSwizzleGreen = new Unsigned32();
    private final Unsigned32 vkComponentSwizzleBlue = new Unsigned32();
    private final Unsigned32 vkComponentSwizzleAlpha = new Unsigned32();
    private final Unsigned32 vkXChromaOffset = new Unsigned32();
    private final Unsigned32 vkYChromaOffset = new Unsigned32();
    private final Enum<WGPUFilterMode> vkChromaFilter = new Enum<>(WGPUFilterMode.class);
    private final Unsigned32 forceExplicitReconstruction = new Unsigned32();
    private final Unsigned64 externalFormat = new Unsigned64();

    private WGPUYCbCrVkDescriptor(){}

    @Deprecated
    public WGPUYCbCrVkDescriptor(Runtime runtime){
        super(runtime);
    }

	/**
	* Creates this struct on the java heap.
	* In general, this should <b>not</b> be used because these structs
	* cannot be directly passed into native code. 
	*/
    public static WGPUYCbCrVkDescriptor createHeap(){
        return new WGPUYCbCrVkDescriptor();
    }

	/**
	* Creates this struct in direct memory.
	* This is how most structs should be created (unless, they
	* are members of a nothing struct)
	* 
	* @see WgpuJavaStruct#useDirectMemory
	*/
    public static WGPUYCbCrVkDescriptor createDirect(){
        var struct = new WGPUYCbCrVkDescriptor();
        struct.useDirectMemory();
        return struct;
    }


    public WGPUChainedStruct getChain(){
        return chain;
    }

    public long getVkFormat(){
        return vkFormat.get();
    }

    public void setVkFormat(long x){
        this.vkFormat.set(x);
    }

    public long getVkYCbCrModel(){
        return vkYCbCrModel.get();
    }

    public void setVkYCbCrModel(long x){
        this.vkYCbCrModel.set(x);
    }

    public long getVkYCbCrRange(){
        return vkYCbCrRange.get();
    }

    public void setVkYCbCrRange(long x){
        this.vkYCbCrRange.set(x);
    }

    public long getVkComponentSwizzleRed(){
        return vkComponentSwizzleRed.get();
    }

    public void setVkComponentSwizzleRed(long x){
        this.vkComponentSwizzleRed.set(x);
    }

    public long getVkComponentSwizzleGreen(){
        return vkComponentSwizzleGreen.get();
    }

    public void setVkComponentSwizzleGreen(long x){
        this.vkComponentSwizzleGreen.set(x);
    }

    public long getVkComponentSwizzleBlue(){
        return vkComponentSwizzleBlue.get();
    }

    public void setVkComponentSwizzleBlue(long x){
        this.vkComponentSwizzleBlue.set(x);
    }

    public long getVkComponentSwizzleAlpha(){
        return vkComponentSwizzleAlpha.get();
    }

    public void setVkComponentSwizzleAlpha(long x){
        this.vkComponentSwizzleAlpha.set(x);
    }

    public long getVkXChromaOffset(){
        return vkXChromaOffset.get();
    }

    public void setVkXChromaOffset(long x){
        this.vkXChromaOffset.set(x);
    }

    public long getVkYChromaOffset(){
        return vkYChromaOffset.get();
    }

    public void setVkYChromaOffset(long x){
        this.vkYChromaOffset.set(x);
    }

    public WGPUFilterMode getVkChromaFilter(){
        return vkChromaFilter.get();
    }

    public void setVkChromaFilter(WGPUFilterMode x){
        this.vkChromaFilter.set(x);
    }

    public long getForceExplicitReconstruction(){
        return forceExplicitReconstruction.get();
    }

    public void setForceExplicitReconstruction(long x){
        this.forceExplicitReconstruction.set(x);
    }

    public @jnr.ffi.types.u_int64_t long getExternalFormat(){
        return externalFormat.get();
    }

    public void setExternalFormat(@jnr.ffi.types.u_int64_t long x){
        this.externalFormat.set(x);
    }

}