package com.monstrous.webgpu;

import com.monstrous.utils.JavaWebGPU;
import com.monstrous.utils.CStrPointer;
import com.monstrous.utils.WgpuJavaStruct;
import com.monstrous.utils.RustCString;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;
import org.jetbrains.annotations.Nullable;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUPipelineLayoutStorageAttachment extends WgpuJavaStruct {

    private final DynamicStructRef<WGPUChainedStruct> nextInChain = new DynamicStructRef<>(WGPUChainedStruct.class);
    private final Struct.Unsigned64 offset = new Struct.Unsigned64();
    private final Struct.Enum<WGPUTextureFormat> format = new Struct.Enum<>(WGPUTextureFormat.class);

    private WGPUPipelineLayoutStorageAttachment(){}

    @Deprecated
    public WGPUPipelineLayoutStorageAttachment(Runtime runtime){
        super(runtime);
    }

	/**
	* Creates this struct on the java heap.
	* In general, this should <b>not</b> be used because these structs
	* cannot be directly passed into native code. 
	*/
    public static WGPUPipelineLayoutStorageAttachment createHeap(){
        return new WGPUPipelineLayoutStorageAttachment();
    }

	/**
	* Creates this struct in direct memory.
	* This is how most structs should be created (unless, they
	* are members of a nothing struct)
	* 
	* @see WgpuJavaStruct#useDirectMemory
	*/
    public static WGPUPipelineLayoutStorageAttachment createDirect(){
        WGPUPipelineLayoutStorageAttachment struct = new WGPUPipelineLayoutStorageAttachment();
        struct.useDirectMemory();
        return struct;
    }


    public DynamicStructRef<WGPUChainedStruct> getNextInChain(){
        return nextInChain;
    }

    public WGPUPipelineLayoutStorageAttachment setNextInChain(WGPUChainedStruct... x){
        if(x.length == 0 || x[0] == null){
            this.nextInChain.set(JavaWebGPU.createNullPointer());
        } else {
            this.nextInChain.set(x);
        }
        return this;
    }

    public @jnr.ffi.types.u_int64_t long getOffset(){
        return offset.get();
    }

    public WGPUPipelineLayoutStorageAttachment setOffset(@jnr.ffi.types.u_int64_t long val){
        this.offset.set(val); return this;
    }

    public WGPUTextureFormat getFormat(){
        return format.get();
    }

    public WGPUPipelineLayoutStorageAttachment setFormat(WGPUTextureFormat val){
        this.format.set(val); return this;
    }

}