package com.monstrous.webgpu;

import com.monstrous.utils.JavaWebGPU;
import com.monstrous.utils.CStrPointer;
import com.monstrous.utils.WgpuJavaStruct;
import com.monstrous.utils.RustCString;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUImageCopyTexture extends WgpuJavaStruct {

    private final Struct.Pointer texture = new Struct.Pointer();
    private final Struct.Unsigned32 mipLevel = new Struct.Unsigned32();
    private final WGPUOrigin3D origin = inner(WGPUOrigin3D.createHeap());
    private final Struct.Enum<WGPUTextureAspect> aspect = new Struct.Enum<>(WGPUTextureAspect.class);

    private WGPUImageCopyTexture(){}

    @Deprecated
    public WGPUImageCopyTexture(Runtime runtime){
        super(runtime);
    }

	/**
	* Creates this struct on the java heap.
	* In general, this should <b>not</b> be used because these structs
	* cannot be directly passed into native code. 
	*/
    public static WGPUImageCopyTexture createHeap(){
        return new WGPUImageCopyTexture();
    }

	/**
	* Creates this struct in direct memory.
	* This is how most structs should be created (unless, they
	* are members of a nothing struct)
	* 
	* @see WgpuJavaStruct#useDirectMemory
	*/
    public static WGPUImageCopyTexture createDirect(){
        WGPUImageCopyTexture struct = new WGPUImageCopyTexture();
        struct.useDirectMemory();
        return struct;
    }


    public jnr.ffi.Pointer getTexture(){
        return texture.get();
    }

    public void setTexture(jnr.ffi.Pointer x){
        this.texture.set(x);
    }

    public long getMipLevel(){
        return mipLevel.get();
    }

    public void setMipLevel(long x){
        this.mipLevel.set(x);
    }

    public WGPUOrigin3D getOrigin(){
        return origin;
    }

    public WGPUTextureAspect getAspect(){
        return aspect.get();
    }

    public void setAspect(WGPUTextureAspect x){
        this.aspect.set(x);
    }

}