package com.monstrous.webgpu;

import com.monstrous.utils.WgpuJavaStruct;
import jnr.ffi.Runtime;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUColor extends WgpuJavaStruct {

    private final Double r = new Double();
    private final Double g = new Double();
    private final Double b = new Double();
    private final Double a = new Double();

    private WGPUColor(){}

    @Deprecated
    public WGPUColor(Runtime runtime){
        super(runtime);
    }

	/**
	* Creates this struct on the java heap.
	* In general, this should <b>not</b> be used because these structs
	* cannot be directly passed into native code. 
	*/
    public static WGPUColor createHeap(){
        return new WGPUColor();
    }

	/**
	* Creates this struct in direct memory.
	* This is how most structs should be created (unless, they
	* are members of a nothing struct)
	* 
	* @see WgpuJavaStruct#useDirectMemory
	*/
    public static WGPUColor createDirect(){
        var struct = new WGPUColor();
        struct.useDirectMemory();
        return struct;
    }


    public double getR(){
        return r.get();
    }

    public void setR(double x){
        this.r.set(x);
    }

    public double getG(){
        return g.get();
    }

    public void setG(double x){
        this.g.set(x);
    }

    public double getB(){
        return b.get();
    }

    public void setB(double x){
        this.b.set(x);
    }

    public double getA(){
        return a.get();
    }

    public void setA(double x){
        this.a.set(x);
    }

}