package com.monstrous.webgpu;

import com.monstrous.utils.JavaWebGPU;
import com.monstrous.utils.CStrPointer;
import com.monstrous.utils.WgpuJavaStruct;
import com.monstrous.utils.RustCString;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUDrmFormatCapabilities extends WgpuJavaStruct {

    private final WGPUChainedStructOut chain = inner(WGPUChainedStructOut.createHeap());
    private final Struct.size_t propertiesCount = new Struct.size_t();
    private final DynamicStructRef<WGPUDrmFormatProperties> properties = new DynamicStructRef<>(WGPUDrmFormatProperties.class);

    private WGPUDrmFormatCapabilities(){}

    @Deprecated
    public WGPUDrmFormatCapabilities(Runtime runtime){
        super(runtime);
    }

	/**
	* Creates this struct on the java heap.
	* In general, this should <b>not</b> be used because these structs
	* cannot be directly passed into native code. 
	*/
    public static WGPUDrmFormatCapabilities createHeap(){
        return new WGPUDrmFormatCapabilities();
    }

	/**
	* Creates this struct in direct memory.
	* This is how most structs should be created (unless, they
	* are members of a nothing struct)
	* 
	* @see WgpuJavaStruct#useDirectMemory
	*/
    public static WGPUDrmFormatCapabilities createDirect(){
        WGPUDrmFormatCapabilities struct = new WGPUDrmFormatCapabilities();
        struct.useDirectMemory();
        return struct;
    }


    public WGPUChainedStructOut getChain(){
        return chain;
    }

    public long getPropertiesCount(){
        return propertiesCount.get();
    }

    public void setPropertiesCount(long x){
        this.propertiesCount.set(x);
    }

    public DynamicStructRef<WGPUDrmFormatProperties> getProperties(){
        return properties;
    }

    public void setProperties(WGPUDrmFormatProperties... x){
        if(x.length == 0 || x[0] == null){
            this.properties.set(JavaWebGPU.createNullPointer());
        } else {
            this.properties.set(x);
        }
    }

}