package com.monstrous.webgpu;

import com.monstrous.utils.WgpuJava;
import com.monstrous.utils.CStrPointer;
import com.monstrous.utils.WgpuJavaStruct;
import com.monstrous.utils.RustCString;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUBufferBindingLayout extends WgpuJavaStruct {

    private final DynamicStructRef<WGPUChainedStruct> nextInChain = new DynamicStructRef<>(WGPUChainedStruct.class);
    private final Enum<WGPUBufferBindingType> type = new Enum<>(WGPUBufferBindingType.class);
    private final Unsigned32 hasDynamicOffset = new Unsigned32();
    private final Unsigned64 minBindingSize = new Unsigned64();

    private WGPUBufferBindingLayout(){}

    @Deprecated
    public WGPUBufferBindingLayout(Runtime runtime){
        super(runtime);
    }

	/**
	* Creates this struct on the java heap.
	* In general, this should <b>not</b> be used because these structs
	* cannot be directly passed into native code. 
	*/
    public static WGPUBufferBindingLayout createHeap(){
        return new WGPUBufferBindingLayout();
    }

	/**
	* Creates this struct in direct memory.
	* This is how most structs should be created (unless, they
	* are members of a nothing struct)
	* 
	* @see WgpuJavaStruct#useDirectMemory
	*/
    public static WGPUBufferBindingLayout createDirect(){
        var struct = new WGPUBufferBindingLayout();
        struct.useDirectMemory();
        return struct;
    }


    public DynamicStructRef<WGPUChainedStruct> getNextInChain(){
        return nextInChain;
    }

    public void setNextInChain(WGPUChainedStruct... x){
        if(x.length == 0 || x[0] == null){
            this.nextInChain.set(WgpuJava.createNullPointer());
        } else {
            this.nextInChain.set(x);
        }
    }

    public WGPUBufferBindingType getType(){
        return type.get();
    }

    public void setType(WGPUBufferBindingType x){
        this.type.set(x);
    }

    public long getHasDynamicOffset(){
        return hasDynamicOffset.get();
    }

    public void setHasDynamicOffset(long x){
        this.hasDynamicOffset.set(x);
    }

    public @jnr.ffi.types.u_int64_t long getMinBindingSize(){
        return minBindingSize.get();
    }

    public void setMinBindingSize(@jnr.ffi.types.u_int64_t long x){
        this.minBindingSize.set(x);
    }

}