package com.monstrous.webgpu;


/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public enum WGPUSharedFenceType {
    Undefined,
    VkSemaphoreOpaqueFD,
    VkSemaphoreSyncFD,
    VkSemaphoreZirconHandle,
    DXGISharedHandle,
    MTLSharedEvent,
}