package com.monstrous.webgpu;

import com.monstrous.utils.WgpuJava;
import com.monstrous.utils.CStrPointer;
import com.monstrous.utils.WgpuJavaStruct;
import com.monstrous.utils.RustCString;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUBlendComponent extends WgpuJavaStruct {

    private final Enum<WGPUBlendOperation> operation = new Enum<>(WGPUBlendOperation.class);
    private final Enum<WGPUBlendFactor> srcFactor = new Enum<>(WGPUBlendFactor.class);
    private final Enum<WGPUBlendFactor> dstFactor = new Enum<>(WGPUBlendFactor.class);

    private WGPUBlendComponent(){}

    @Deprecated
    public WGPUBlendComponent(Runtime runtime){
        super(runtime);
    }

	/**
	* Creates this struct on the java heap.
	* In general, this should <b>not</b> be used because these structs
	* cannot be directly passed into native code. 
	*/
    public static WGPUBlendComponent createHeap(){
        return new WGPUBlendComponent();
    }

	/**
	* Creates this struct in direct memory.
	* This is how most structs should be created (unless, they
	* are members of a nothing struct)
	* 
	* @see WgpuJavaStruct#useDirectMemory
	*/
    public static WGPUBlendComponent createDirect(){
        var struct = new WGPUBlendComponent();
        struct.useDirectMemory();
        return struct;
    }


    public WGPUBlendOperation getOperation(){
        return operation.get();
    }

    public void setOperation(WGPUBlendOperation x){
        this.operation.set(x);
    }

    public WGPUBlendFactor getSrcFactor(){
        return srcFactor.get();
    }

    public void setSrcFactor(WGPUBlendFactor x){
        this.srcFactor.set(x);
    }

    public WGPUBlendFactor getDstFactor(){
        return dstFactor.get();
    }

    public void setDstFactor(WGPUBlendFactor x){
        this.dstFactor.set(x);
    }

}