package com.monstrous.webgpu;

import com.monstrous.utils.JavaWebGPU;
import com.monstrous.utils.CStrPointer;
import com.monstrous.utils.WgpuJavaStruct;
import com.monstrous.utils.RustCString;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;
import org.jetbrains.annotations.Nullable;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUBlendComponent extends WgpuJavaStruct {

    private final Struct.Enum<WGPUBlendOperation> operation = new Struct.Enum<>(WGPUBlendOperation.class);
    private final Struct.Enum<WGPUBlendFactor> srcFactor = new Struct.Enum<>(WGPUBlendFactor.class);
    private final Struct.Enum<WGPUBlendFactor> dstFactor = new Struct.Enum<>(WGPUBlendFactor.class);

    private WGPUBlendComponent(){}

    @Deprecated
    public WGPUBlendComponent(Runtime runtime){
        super(runtime);
    }

	/**
	* Creates this struct on the java heap.
	* In general, this should <b>not</b> be used because these structs
	* cannot be directly passed into native code. 
	*/
    public static WGPUBlendComponent createHeap(){
        return new WGPUBlendComponent();
    }

	/**
	* Creates this struct in direct memory.
	* This is how most structs should be created (unless, they
	* are members of a nothing struct)
	* 
	* @see WgpuJavaStruct#useDirectMemory
	*/
    public static WGPUBlendComponent createDirect(){
        WGPUBlendComponent struct = new WGPUBlendComponent();
        struct.useDirectMemory();
        return struct;
    }


    public WGPUBlendOperation getOperation(){
        return operation.get();
    }

    public WGPUBlendComponent setOperation(WGPUBlendOperation val){
        this.operation.set(val); return this;
    }

    public WGPUBlendFactor getSrcFactor(){
        return srcFactor.get();
    }

    public WGPUBlendComponent setSrcFactor(WGPUBlendFactor val){
        this.srcFactor.set(val); return this;
    }

    public WGPUBlendFactor getDstFactor(){
        return dstFactor.get();
    }

    public WGPUBlendComponent setDstFactor(WGPUBlendFactor val){
        this.dstFactor.set(val); return this;
    }

}