package com.monstrous.webgpu;

import com.monstrous.wgpuUtils.CStrPointer;
import com.monstrous.wgpuUtils.RustCString;
import com.monstrous.wgpuUtils.WgpuJavaStruct;
import jnr.ffi.Runtime;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUShaderModuleWGSLDescriptor extends WgpuJavaStruct {

    private final WGPUChainedStruct chain = inner(WGPUChainedStruct.createHeap());
    private final @CStrPointer Pointer code = new Pointer();

    private WGPUShaderModuleWGSLDescriptor(){}

    @Deprecated
    public WGPUShaderModuleWGSLDescriptor(Runtime runtime){
        super(runtime);
    }

	/**
	* Creates this struct on the java heap.
	* In general, this should <b>not</b> be used because these structs
	* cannot be directly passed into native code. 
	*/
    public static WGPUShaderModuleWGSLDescriptor createHeap(){
        return new WGPUShaderModuleWGSLDescriptor();
    }

	/**
	* Creates this struct in direct memory.
	* This is how most structs should be created (unless, they
	* are members of a nothing struct)
	* 
	* @see WgpuJavaStruct#useDirectMemory
	*/
    public static WGPUShaderModuleWGSLDescriptor createDirect(){
        var struct = new WGPUShaderModuleWGSLDescriptor();
        struct.useDirectMemory();
        return struct;
    }


    public WGPUChainedStruct getChain(){
        return chain;
    }

    public java.lang.String getCode(){
        return RustCString.fromPointer(code.get());
    }

    public void setCode(java.lang.String x){
        this.code.set(RustCString.toPointer(x));
    }

}