package com.monstrous.webgpu;

import com.monstrous.utils.JavaWebGPU;
import com.monstrous.utils.CStrPointer;
import com.monstrous.utils.WgpuJavaStruct;
import com.monstrous.utils.RustCString;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUSharedTextureMemoryDmaBufDescriptor extends WgpuJavaStruct {

    private final WGPUChainedStruct chain = inner(WGPUChainedStruct.createHeap());
    private final WGPUExtent3D size = inner(WGPUExtent3D.createHeap());
    private final Struct.Unsigned32 drmFormat = new Struct.Unsigned32();
    private final Struct.Unsigned64 drmModifier = new Struct.Unsigned64();
    private final Struct.size_t planeCount = new Struct.size_t();
    private final DynamicStructRef<WGPUSharedTextureMemoryDmaBufPlane> planes = new DynamicStructRef<>(WGPUSharedTextureMemoryDmaBufPlane.class);

    private WGPUSharedTextureMemoryDmaBufDescriptor(){}

    @Deprecated
    public WGPUSharedTextureMemoryDmaBufDescriptor(Runtime runtime){
        super(runtime);
    }

	/**
	* Creates this struct on the java heap.
	* In general, this should <b>not</b> be used because these structs
	* cannot be directly passed into native code. 
	*/
    public static WGPUSharedTextureMemoryDmaBufDescriptor createHeap(){
        return new WGPUSharedTextureMemoryDmaBufDescriptor();
    }

	/**
	* Creates this struct in direct memory.
	* This is how most structs should be created (unless, they
	* are members of a nothing struct)
	* 
	* @see WgpuJavaStruct#useDirectMemory
	*/
    public static WGPUSharedTextureMemoryDmaBufDescriptor createDirect(){
        WGPUSharedTextureMemoryDmaBufDescriptor struct = new WGPUSharedTextureMemoryDmaBufDescriptor();
        struct.useDirectMemory();
        return struct;
    }


    public WGPUChainedStruct getChain(){
        return chain;
    }

    public WGPUExtent3D getSize(){
        return size;
    }

    public long getDrmFormat(){
        return drmFormat.get();
    }

    public void setDrmFormat(long x){
        this.drmFormat.set(x);
    }

    public @jnr.ffi.types.u_int64_t long getDrmModifier(){
        return drmModifier.get();
    }

    public void setDrmModifier(@jnr.ffi.types.u_int64_t long x){
        this.drmModifier.set(x);
    }

    public long getPlaneCount(){
        return planeCount.get();
    }

    public void setPlaneCount(long x){
        this.planeCount.set(x);
    }

    public DynamicStructRef<WGPUSharedTextureMemoryDmaBufPlane> getPlanes(){
        return planes;
    }

    public void setPlanes(WGPUSharedTextureMemoryDmaBufPlane... x){
        if(x.length == 0 || x[0] == null){
            this.planes.set(JavaWebGPU.createNullPointer());
        } else {
            this.planes.set(x);
        }
    }

}