package com.monstrous.webgpu;


/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public enum WGPUDeviceLostReason {
    Undefined,
    Unknown,
    Destroyed,
    InstanceDropped,
    FailedCreation,
}