package com.monstrous.webgpu;


/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public enum WGPUErrorType {
    NoError,
    Validation,
    OutOfMemory,
    Internal,
    Unknown,
    DeviceLost,
}