package com.monstrous.webgpu;

import com.monstrous.utils.JavaWebGPU;
import com.monstrous.utils.CStrPointer;
import com.monstrous.utils.WgpuJavaStruct;
import com.monstrous.utils.RustCString;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;
import org.jetbrains.annotations.Nullable;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUTextureBindingViewDimensionDescriptor extends WgpuJavaStruct {

    private final WGPUChainedStruct chain = inner(WGPUChainedStruct.createHeap());
    private final Struct.Enum<WGPUTextureViewDimension> textureBindingViewDimension = new Struct.Enum<>(WGPUTextureViewDimension.class);

    private WGPUTextureBindingViewDimensionDescriptor(){}

    @Deprecated
    public WGPUTextureBindingViewDimensionDescriptor(Runtime runtime){
        super(runtime);
    }

	/**
	* Creates this struct on the java heap.
	* In general, this should <b>not</b> be used because these structs
	* cannot be directly passed into native code. 
	*/
    public static WGPUTextureBindingViewDimensionDescriptor createHeap(){
        return new WGPUTextureBindingViewDimensionDescriptor();
    }

	/**
	* Creates this struct in direct memory.
	* This is how most structs should be created (unless, they
	* are members of a nothing struct)
	* 
	* @see WgpuJavaStruct#useDirectMemory
	*/
    public static WGPUTextureBindingViewDimensionDescriptor createDirect(){
        WGPUTextureBindingViewDimensionDescriptor struct = new WGPUTextureBindingViewDimensionDescriptor();
        struct.useDirectMemory();
        return struct;
    }


    public WGPUChainedStruct getChain(){
        return chain;
    }

    public WGPUTextureViewDimension getTextureBindingViewDimension(){
        return textureBindingViewDimension.get();
    }

    public WGPUTextureBindingViewDimensionDescriptor setTextureBindingViewDimension(WGPUTextureViewDimension val){
        this.textureBindingViewDimension.set(val); return this;
    }

}