package com.monstrous.webgpu;

import com.monstrous.utils.JavaWebGPU;
import com.monstrous.utils.CStrPointer;
import com.monstrous.utils.WgpuJavaStruct;
import com.monstrous.utils.RustCString;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUBindGroupLayoutDescriptor extends WgpuJavaStruct {

    private final DynamicStructRef<WGPUChainedStruct> nextInChain = new DynamicStructRef<>(WGPUChainedStruct.class);
    private final @CStrPointer Struct.Pointer label = new Struct.Pointer();
    private final Struct.size_t entryCount = new Struct.size_t();
    private final DynamicStructRef<WGPUBindGroupLayoutEntry> entries = new DynamicStructRef<>(WGPUBindGroupLayoutEntry.class);

    private WGPUBindGroupLayoutDescriptor(){}

    @Deprecated
    public WGPUBindGroupLayoutDescriptor(Runtime runtime){
        super(runtime);
    }

	/**
	* Creates this struct on the java heap.
	* In general, this should <b>not</b> be used because these structs
	* cannot be directly passed into native code. 
	*/
    public static WGPUBindGroupLayoutDescriptor createHeap(){
        return new WGPUBindGroupLayoutDescriptor();
    }

	/**
	* Creates this struct in direct memory.
	* This is how most structs should be created (unless, they
	* are members of a nothing struct)
	* 
	* @see WgpuJavaStruct#useDirectMemory
	*/
    public static WGPUBindGroupLayoutDescriptor createDirect(){
        WGPUBindGroupLayoutDescriptor struct = new WGPUBindGroupLayoutDescriptor();
        struct.useDirectMemory();
        return struct;
    }


    public DynamicStructRef<WGPUChainedStruct> getNextInChain(){
        return nextInChain;
    }

    public void setNextInChain(WGPUChainedStruct... x){
        if(x.length == 0 || x[0] == null){
            this.nextInChain.set(JavaWebGPU.createNullPointer());
        } else {
            this.nextInChain.set(x);
        }
    }

    public java.lang.String getLabel(){
        return RustCString.fromPointer(label.get());
    }

    public void setLabel(java.lang.String x){
        this.label.set(RustCString.toPointer(x));
    }

    public long getEntryCount(){
        return entryCount.get();
    }

    public void setEntryCount(long x){
        this.entryCount.set(x);
    }

    public DynamicStructRef<WGPUBindGroupLayoutEntry> getEntries(){
        return entries;
    }

    public void setEntries(WGPUBindGroupLayoutEntry... x){
        if(x.length == 0 || x[0] == null){
            this.entries.set(JavaWebGPU.createNullPointer());
        } else {
            this.entries.set(x);
        }
    }

}