package com.monstrous.webgpu;


/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public enum WGPURequestAdapterStatus {
    Success,
    InstanceDropped,
    Unavailable,
    Error,
    Unknown,
}