package com.monstrous.webgpu;

import com.monstrous.utils.JavaWebGPU;
import com.monstrous.utils.WgpuJavaStruct;
import jnr.ffi.Runtime;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUChainedStructOut extends WgpuJavaStruct {

    private final DynamicStructRef<WGPUChainedStructOut> next = new DynamicStructRef<>(WGPUChainedStructOut.class);
    private final Unsigned32 sType = new Unsigned32();

    private WGPUChainedStructOut(){}

    @Deprecated
    public WGPUChainedStructOut(Runtime runtime){
        super(runtime);
    }

	/**
	* Creates this struct on the java heap.
	* In general, this should <b>not</b> be used because these structs
	* cannot be directly passed into native code. 
	*/
    public static WGPUChainedStructOut createHeap(){
        return new WGPUChainedStructOut();
    }

	/**
	* Creates this struct in direct memory.
	* This is how most structs should be created (unless, they
	* are members of a nothing struct)
	* 
	* @see WgpuJavaStruct#useDirectMemory
	*/
    public static WGPUChainedStructOut createDirect(){
        var struct = new WGPUChainedStructOut();
        struct.useDirectMemory();
        return struct;
    }


    public DynamicStructRef<WGPUChainedStructOut> getNext(){
        return next;
    }

    public void setNext(WGPUChainedStructOut... x){
        if(x.length == 0 || x[0] == null){
            this.next.set(JavaWebGPU.createNullPointer());
        } else {
            this.next.set(x);
        }
    }

    public long getSType(){
        return sType.get();
    }

    public void setSType(long x){
        this.sType.set(x);
    }

}