package com.monstrous.webgpu;

import com.monstrous.utils.JavaWebGPU;
import com.monstrous.utils.CStrPointer;
import com.monstrous.utils.WgpuJavaStruct;
import com.monstrous.utils.RustCString;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;
import org.jetbrains.annotations.Nullable;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUAdapterPropertiesVk extends WgpuJavaStruct {

    private final WGPUChainedStructOut chain = inner(WGPUChainedStructOut.createHeap());
    private final Struct.Unsigned32 driverVersion = new Struct.Unsigned32();

    private WGPUAdapterPropertiesVk(){}

    @Deprecated
    public WGPUAdapterPropertiesVk(Runtime runtime){
        super(runtime);
    }

	/**
	* Creates this struct on the java heap.
	* In general, this should <b>not</b> be used because these structs
	* cannot be directly passed into native code. 
	*/
    public static WGPUAdapterPropertiesVk createHeap(){
        return new WGPUAdapterPropertiesVk();
    }

	/**
	* Creates this struct in direct memory.
	* This is how most structs should be created (unless, they
	* are members of a nothing struct)
	* 
	* @see WgpuJavaStruct#useDirectMemory
	*/
    public static WGPUAdapterPropertiesVk createDirect(){
        WGPUAdapterPropertiesVk struct = new WGPUAdapterPropertiesVk();
        struct.useDirectMemory();
        return struct;
    }


    public WGPUChainedStructOut getChain(){
        return chain;
    }

    public long getDriverVersion(){
        return driverVersion.get();
    }

    public WGPUAdapterPropertiesVk setDriverVersion(long val){
        this.driverVersion.set(val); return this;
    }

}