package com.monstrous.webgpu;

import com.monstrous.utils.WgpuJava;
import com.monstrous.utils.CStrPointer;
import com.monstrous.utils.WgpuJavaStruct;
import com.monstrous.utils.RustCString;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUSharedTextureMemoryOpaqueFDDescriptor extends WgpuJavaStruct {

    private final WGPUChainedStruct chain = inner(WGPUChainedStruct.createHeap());
    private final Pointer vkImageCreateInfo = new Pointer();
    private final Unsigned32 memoryFD = new Unsigned32();
    private final Unsigned32 memoryTypeIndex = new Unsigned32();
    private final Unsigned64 allocationSize = new Unsigned64();
    private final Unsigned32 dedicatedAllocation = new Unsigned32();

    private WGPUSharedTextureMemoryOpaqueFDDescriptor(){}

    @Deprecated
    public WGPUSharedTextureMemoryOpaqueFDDescriptor(Runtime runtime){
        super(runtime);
    }

	/**
	* Creates this struct on the java heap.
	* In general, this should <b>not</b> be used because these structs
	* cannot be directly passed into native code. 
	*/
    public static WGPUSharedTextureMemoryOpaqueFDDescriptor createHeap(){
        return new WGPUSharedTextureMemoryOpaqueFDDescriptor();
    }

	/**
	* Creates this struct in direct memory.
	* This is how most structs should be created (unless, they
	* are members of a nothing struct)
	* 
	* @see WgpuJavaStruct#useDirectMemory
	*/
    public static WGPUSharedTextureMemoryOpaqueFDDescriptor createDirect(){
        var struct = new WGPUSharedTextureMemoryOpaqueFDDescriptor();
        struct.useDirectMemory();
        return struct;
    }


    public WGPUChainedStruct getChain(){
        return chain;
    }

    public jnr.ffi.Pointer getVkImageCreateInfo(){
        return vkImageCreateInfo.get();
    }

    public void setVkImageCreateInfo(jnr.ffi.Pointer x){
        this.vkImageCreateInfo.set(x);
    }

    public long getMemoryFD(){
        return memoryFD.get();
    }

    public void setMemoryFD(long x){
        this.memoryFD.set(x);
    }

    public long getMemoryTypeIndex(){
        return memoryTypeIndex.get();
    }

    public void setMemoryTypeIndex(long x){
        this.memoryTypeIndex.set(x);
    }

    public @jnr.ffi.types.u_int64_t long getAllocationSize(){
        return allocationSize.get();
    }

    public void setAllocationSize(@jnr.ffi.types.u_int64_t long x){
        this.allocationSize.set(x);
    }

    public long getDedicatedAllocation(){
        return dedicatedAllocation.get();
    }

    public void setDedicatedAllocation(long x){
        this.dedicatedAllocation.set(x);
    }

}