package com.monstrous.webgpu;

import com.monstrous.utils.JavaWebGPU;
import com.monstrous.utils.CStrPointer;
import com.monstrous.utils.WgpuJavaStruct;
import com.monstrous.utils.RustCString;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUDawnRenderPassColorAttachmentRenderToSingleSampled extends WgpuJavaStruct {

    private final WGPUChainedStruct chain = inner(WGPUChainedStruct.createHeap());
    private final Struct.Unsigned32 implicitSampleCount = new Struct.Unsigned32();

    private WGPUDawnRenderPassColorAttachmentRenderToSingleSampled(){}

    @Deprecated
    public WGPUDawnRenderPassColorAttachmentRenderToSingleSampled(Runtime runtime){
        super(runtime);
    }

	/**
	* Creates this struct on the java heap.
	* In general, this should <b>not</b> be used because these structs
	* cannot be directly passed into native code. 
	*/
    public static WGPUDawnRenderPassColorAttachmentRenderToSingleSampled createHeap(){
        return new WGPUDawnRenderPassColorAttachmentRenderToSingleSampled();
    }

	/**
	* Creates this struct in direct memory.
	* This is how most structs should be created (unless, they
	* are members of a nothing struct)
	* 
	* @see WgpuJavaStruct#useDirectMemory
	*/
    public static WGPUDawnRenderPassColorAttachmentRenderToSingleSampled createDirect(){
        WGPUDawnRenderPassColorAttachmentRenderToSingleSampled struct = new WGPUDawnRenderPassColorAttachmentRenderToSingleSampled();
        struct.useDirectMemory();
        return struct;
    }


    public WGPUChainedStruct getChain(){
        return chain;
    }

    public long getImplicitSampleCount(){
        return implicitSampleCount.get();
    }

    public void setImplicitSampleCount(long x){
        this.implicitSampleCount.set(x);
    }

}