package com.monstrous.webgpu;

import com.monstrous.utils.WgpuJava;
import com.monstrous.utils.CStrPointer;
import com.monstrous.utils.WgpuJavaStruct;
import com.monstrous.utils.RustCString;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUVertexBufferLayout extends WgpuJavaStruct {

    private final Unsigned64 arrayStride = new Unsigned64();
    private final Enum<WGPUVertexStepMode> stepMode = new Enum<>(WGPUVertexStepMode.class);
    private final size_t attributeCount = new size_t();
    private final DynamicStructRef<WGPUVertexAttribute> attributes = new DynamicStructRef<>(WGPUVertexAttribute.class);

    private WGPUVertexBufferLayout(){}

    @Deprecated
    public WGPUVertexBufferLayout(Runtime runtime){
        super(runtime);
    }

	/**
	* Creates this struct on the java heap.
	* In general, this should <b>not</b> be used because these structs
	* cannot be directly passed into native code. 
	*/
    public static WGPUVertexBufferLayout createHeap(){
        return new WGPUVertexBufferLayout();
    }

	/**
	* Creates this struct in direct memory.
	* This is how most structs should be created (unless, they
	* are members of a nothing struct)
	* 
	* @see WgpuJavaStruct#useDirectMemory
	*/
    public static WGPUVertexBufferLayout createDirect(){
        var struct = new WGPUVertexBufferLayout();
        struct.useDirectMemory();
        return struct;
    }


    public @jnr.ffi.types.u_int64_t long getArrayStride(){
        return arrayStride.get();
    }

    public void setArrayStride(@jnr.ffi.types.u_int64_t long x){
        this.arrayStride.set(x);
    }

    public WGPUVertexStepMode getStepMode(){
        return stepMode.get();
    }

    public void setStepMode(WGPUVertexStepMode x){
        this.stepMode.set(x);
    }

    public long getAttributeCount(){
        return attributeCount.get();
    }

    public void setAttributeCount(long x){
        this.attributeCount.set(x);
    }

    public DynamicStructRef<WGPUVertexAttribute> getAttributes(){
        return attributes;
    }

    public void setAttributes(WGPUVertexAttribute... x){
        if(x.length == 0 || x[0] == null){
            this.attributes.set(WgpuJava.createNullPointer());
        } else {
            this.attributes.set(x);
        }
    }

}