package com.monstrous.webgpu;

import com.monstrous.utils.WgpuJava;
import com.monstrous.utils.CStrPointer;
import com.monstrous.utils.WgpuJavaStruct;
import com.monstrous.utils.RustCString;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUDawnTogglesDescriptor extends WgpuJavaStruct {

    private final WGPUChainedStruct chain = inner(WGPUChainedStruct.createHeap());
    private final size_t enabledToggleCount = new size_t();
    private final Pointer enabledToggles = new Pointer();
    private final size_t disabledToggleCount = new size_t();
    private final Pointer disabledToggles = new Pointer();

    private WGPUDawnTogglesDescriptor(){}

    @Deprecated
    public WGPUDawnTogglesDescriptor(Runtime runtime){
        super(runtime);
    }

	/**
	* Creates this struct on the java heap.
	* In general, this should <b>not</b> be used because these structs
	* cannot be directly passed into native code. 
	*/
    public static WGPUDawnTogglesDescriptor createHeap(){
        return new WGPUDawnTogglesDescriptor();
    }

	/**
	* Creates this struct in direct memory.
	* This is how most structs should be created (unless, they
	* are members of a nothing struct)
	* 
	* @see WgpuJavaStruct#useDirectMemory
	*/
    public static WGPUDawnTogglesDescriptor createDirect(){
        var struct = new WGPUDawnTogglesDescriptor();
        struct.useDirectMemory();
        return struct;
    }


    public WGPUChainedStruct getChain(){
        return chain;
    }

    public long getEnabledToggleCount(){
        return enabledToggleCount.get();
    }

    public void setEnabledToggleCount(long x){
        this.enabledToggleCount.set(x);
    }

    public jnr.ffi.Pointer getEnabledToggles(){
        return enabledToggles.get();
    }

    public void setEnabledToggles(jnr.ffi.Pointer x){
        this.enabledToggles.set(x);
    }

    public long getDisabledToggleCount(){
        return disabledToggleCount.get();
    }

    public void setDisabledToggleCount(long x){
        this.disabledToggleCount.set(x);
    }

    public jnr.ffi.Pointer getDisabledToggles(){
        return disabledToggles.get();
    }

    public void setDisabledToggles(jnr.ffi.Pointer x){
        this.disabledToggles.set(x);
    }

}