package com.monstrous.webgpu;

import com.monstrous.utils.WgpuJava;
import com.monstrous.utils.CStrPointer;
import com.monstrous.utils.WgpuJavaStruct;
import com.monstrous.utils.RustCString;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUSharedTextureMemoryDXGISharedHandleDescriptor extends WgpuJavaStruct {

    private final WGPUChainedStruct chain = inner(WGPUChainedStruct.createHeap());
    private final Pointer handle = new Pointer();
    private final Unsigned32 useKeyedMutex = new Unsigned32();

    private WGPUSharedTextureMemoryDXGISharedHandleDescriptor(){}

    @Deprecated
    public WGPUSharedTextureMemoryDXGISharedHandleDescriptor(Runtime runtime){
        super(runtime);
    }

	/**
	* Creates this struct on the java heap.
	* In general, this should <b>not</b> be used because these structs
	* cannot be directly passed into native code. 
	*/
    public static WGPUSharedTextureMemoryDXGISharedHandleDescriptor createHeap(){
        return new WGPUSharedTextureMemoryDXGISharedHandleDescriptor();
    }

	/**
	* Creates this struct in direct memory.
	* This is how most structs should be created (unless, they
	* are members of a nothing struct)
	* 
	* @see WgpuJavaStruct#useDirectMemory
	*/
    public static WGPUSharedTextureMemoryDXGISharedHandleDescriptor createDirect(){
        var struct = new WGPUSharedTextureMemoryDXGISharedHandleDescriptor();
        struct.useDirectMemory();
        return struct;
    }


    public WGPUChainedStruct getChain(){
        return chain;
    }

    public jnr.ffi.Pointer getHandle(){
        return handle.get();
    }

    public void setHandle(jnr.ffi.Pointer x){
        this.handle.set(x);
    }

    public long getUseKeyedMutex(){
        return useKeyedMutex.get();
    }

    public void setUseKeyedMutex(long x){
        this.useKeyedMutex.set(x);
    }

}