package com.monstrous.webgpu;

import com.monstrous.utils.WgpuJava;
import com.monstrous.utils.CStrPointer;
import com.monstrous.utils.WgpuJavaStruct;
import com.monstrous.utils.RustCString;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUSharedFenceMTLSharedEventExportInfo extends WgpuJavaStruct {

    private final WGPUChainedStructOut chain = inner(WGPUChainedStructOut.createHeap());
    private final Pointer sharedEvent = new Pointer();

    private WGPUSharedFenceMTLSharedEventExportInfo(){}

    @Deprecated
    public WGPUSharedFenceMTLSharedEventExportInfo(Runtime runtime){
        super(runtime);
    }

	/**
	* Creates this struct on the java heap.
	* In general, this should <b>not</b> be used because these structs
	* cannot be directly passed into native code. 
	*/
    public static WGPUSharedFenceMTLSharedEventExportInfo createHeap(){
        return new WGPUSharedFenceMTLSharedEventExportInfo();
    }

	/**
	* Creates this struct in direct memory.
	* This is how most structs should be created (unless, they
	* are members of a nothing struct)
	* 
	* @see WgpuJavaStruct#useDirectMemory
	*/
    public static WGPUSharedFenceMTLSharedEventExportInfo createDirect(){
        var struct = new WGPUSharedFenceMTLSharedEventExportInfo();
        struct.useDirectMemory();
        return struct;
    }


    public WGPUChainedStructOut getChain(){
        return chain;
    }

    public jnr.ffi.Pointer getSharedEvent(){
        return sharedEvent.get();
    }

    public void setSharedEvent(jnr.ffi.Pointer x){
        this.sharedEvent.set(x);
    }

}