package com.monstrous.webgpu;

import com.monstrous.utils.JavaWebGPU;
import com.monstrous.utils.CStrPointer;
import com.monstrous.utils.WgpuJavaStruct;
import com.monstrous.utils.RustCString;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;
import org.jetbrains.annotations.Nullable;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUBufferHostMappedPointer extends WgpuJavaStruct {

    private final WGPUChainedStruct chain = inner(WGPUChainedStruct.createHeap());
    private final Struct.Pointer pointer = new Struct.Pointer();
    private final Struct.Pointer disposeCallback = new Struct.Pointer();
    private final Struct.Pointer userdata = new Struct.Pointer();

    private WGPUBufferHostMappedPointer(){}

    @Deprecated
    public WGPUBufferHostMappedPointer(Runtime runtime){
        super(runtime);
    }

	/**
	* Creates this struct on the java heap.
	* In general, this should <b>not</b> be used because these structs
	* cannot be directly passed into native code. 
	*/
    public static WGPUBufferHostMappedPointer createHeap(){
        return new WGPUBufferHostMappedPointer();
    }

	/**
	* Creates this struct in direct memory.
	* This is how most structs should be created (unless, they
	* are members of a nothing struct)
	* 
	* @see WgpuJavaStruct#useDirectMemory
	*/
    public static WGPUBufferHostMappedPointer createDirect(){
        WGPUBufferHostMappedPointer struct = new WGPUBufferHostMappedPointer();
        struct.useDirectMemory();
        return struct;
    }


    public WGPUChainedStruct getChain(){
        return chain;
    }

    public jnr.ffi.Pointer getPointer(){
        return pointer.get();
    }

    public WGPUBufferHostMappedPointer setPointer(jnr.ffi.Pointer val){
        this.pointer.set(val); return this;
    }

    public jnr.ffi.Pointer getDisposeCallback(){
        return disposeCallback.get();
    }

    public WGPUBufferHostMappedPointer setDisposeCallback(jnr.ffi.Pointer val){
        this.disposeCallback.set(val); return this;
    }

    public jnr.ffi.Pointer getUserdata(){
        return userdata.get();
    }

    public WGPUBufferHostMappedPointer setUserdata(jnr.ffi.Pointer val){
        this.userdata.set(val); return this;
    }

}