package com.monstrous.webgpu;

import com.monstrous.utils.JavaWebGPU;
import com.monstrous.utils.CStrPointer;
import com.monstrous.utils.WgpuJavaStruct;
import com.monstrous.utils.RustCString;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;
import org.jetbrains.annotations.Nullable;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUVertexAttribute extends WgpuJavaStruct {

    private final Struct.Enum<WGPUVertexFormat> format = new Struct.Enum<>(WGPUVertexFormat.class);
    private final Struct.Unsigned64 offset = new Struct.Unsigned64();
    private final Struct.Unsigned32 shaderLocation = new Struct.Unsigned32();

    private WGPUVertexAttribute(){}

    @Deprecated
    public WGPUVertexAttribute(Runtime runtime){
        super(runtime);
    }

	/**
	* Creates this struct on the java heap.
	* In general, this should <b>not</b> be used because these structs
	* cannot be directly passed into native code. 
	*/
    public static WGPUVertexAttribute createHeap(){
        return new WGPUVertexAttribute();
    }

	/**
	* Creates this struct in direct memory.
	* This is how most structs should be created (unless, they
	* are members of a nothing struct)
	* 
	* @see WgpuJavaStruct#useDirectMemory
	*/
    public static WGPUVertexAttribute createDirect(){
        WGPUVertexAttribute struct = new WGPUVertexAttribute();
        struct.useDirectMemory();
        return struct;
    }


    public WGPUVertexFormat getFormat(){
        return format.get();
    }

    public WGPUVertexAttribute setFormat(WGPUVertexFormat val){
        this.format.set(val); return this;
    }

    public @jnr.ffi.types.u_int64_t long getOffset(){
        return offset.get();
    }

    public WGPUVertexAttribute setOffset(@jnr.ffi.types.u_int64_t long val){
        this.offset.set(val); return this;
    }

    public long getShaderLocation(){
        return shaderLocation.get();
    }

    public WGPUVertexAttribute setShaderLocation(long val){
        this.shaderLocation.set(val); return this;
    }

}