package com.monstrous.webgpu;

import com.monstrous.utils.JavaWebGPU;
import com.monstrous.utils.CStrPointer;
import com.monstrous.utils.WgpuJavaStruct;
import com.monstrous.utils.RustCString;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;
import org.jetbrains.annotations.Nullable;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUSharedTextureMemoryIOSurfaceDescriptor extends WgpuJavaStruct {

    private final WGPUChainedStruct chain = inner(WGPUChainedStruct.createHeap());
    private final Struct.Pointer ioSurface = new Struct.Pointer();

    private WGPUSharedTextureMemoryIOSurfaceDescriptor(){}

    @Deprecated
    public WGPUSharedTextureMemoryIOSurfaceDescriptor(Runtime runtime){
        super(runtime);
    }

	/**
	* Creates this struct on the java heap.
	* In general, this should <b>not</b> be used because these structs
	* cannot be directly passed into native code. 
	*/
    public static WGPUSharedTextureMemoryIOSurfaceDescriptor createHeap(){
        return new WGPUSharedTextureMemoryIOSurfaceDescriptor();
    }

	/**
	* Creates this struct in direct memory.
	* This is how most structs should be created (unless, they
	* are members of a nothing struct)
	* 
	* @see WgpuJavaStruct#useDirectMemory
	*/
    public static WGPUSharedTextureMemoryIOSurfaceDescriptor createDirect(){
        WGPUSharedTextureMemoryIOSurfaceDescriptor struct = new WGPUSharedTextureMemoryIOSurfaceDescriptor();
        struct.useDirectMemory();
        return struct;
    }


    public WGPUChainedStruct getChain(){
        return chain;
    }

    public jnr.ffi.Pointer getIoSurface(){
        return ioSurface.get();
    }

    public WGPUSharedTextureMemoryIOSurfaceDescriptor setIoSurface(jnr.ffi.Pointer val){
        this.ioSurface.set(val); return this;
    }

}