package com.monstrous.webgpu;

import com.monstrous.utils.WgpuJava;
import com.monstrous.utils.CStrPointer;
import com.monstrous.utils.WgpuJavaStruct;
import com.monstrous.utils.RustCString;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUColorTargetStateExpandResolveTextureDawn extends WgpuJavaStruct {

    private final WGPUChainedStruct chain = inner(WGPUChainedStruct.createHeap());
    private final Unsigned32 enabled = new Unsigned32();

    private WGPUColorTargetStateExpandResolveTextureDawn(){}

    @Deprecated
    public WGPUColorTargetStateExpandResolveTextureDawn(Runtime runtime){
        super(runtime);
    }

	/**
	* Creates this struct on the java heap.
	* In general, this should <b>not</b> be used because these structs
	* cannot be directly passed into native code. 
	*/
    public static WGPUColorTargetStateExpandResolveTextureDawn createHeap(){
        return new WGPUColorTargetStateExpandResolveTextureDawn();
    }

	/**
	* Creates this struct in direct memory.
	* This is how most structs should be created (unless, they
	* are members of a nothing struct)
	* 
	* @see WgpuJavaStruct#useDirectMemory
	*/
    public static WGPUColorTargetStateExpandResolveTextureDawn createDirect(){
        var struct = new WGPUColorTargetStateExpandResolveTextureDawn();
        struct.useDirectMemory();
        return struct;
    }


    public WGPUChainedStruct getChain(){
        return chain;
    }

    public long getEnabled(){
        return enabled.get();
    }

    public void setEnabled(long x){
        this.enabled.set(x);
    }

}