package com.monstrous.webgpu;

import com.monstrous.utils.JavaWebGPU;
import com.monstrous.utils.CStrPointer;
import com.monstrous.utils.WgpuJavaStruct;
import com.monstrous.utils.RustCString;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;
import org.jetbrains.annotations.Nullable;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUPipelineLayoutDescriptor extends WgpuJavaStruct {

    private final DynamicStructRef<WGPUChainedStruct> nextInChain = new DynamicStructRef<>(WGPUChainedStruct.class);
    private final @Nullable @CStrPointer Struct.Pointer label = new Struct.Pointer();
    private final Struct.size_t bindGroupLayoutCount = new Struct.size_t();
    private final Struct.Pointer bindGroupLayouts = new Struct.Pointer();

    private WGPUPipelineLayoutDescriptor(){}

    @Deprecated
    public WGPUPipelineLayoutDescriptor(Runtime runtime){
        super(runtime);
    }

	/**
	* Creates this struct on the java heap.
	* In general, this should <b>not</b> be used because these structs
	* cannot be directly passed into native code. 
	*/
    public static WGPUPipelineLayoutDescriptor createHeap(){
        return new WGPUPipelineLayoutDescriptor();
    }

	/**
	* Creates this struct in direct memory.
	* This is how most structs should be created (unless, they
	* are members of a nothing struct)
	* 
	* @see WgpuJavaStruct#useDirectMemory
	*/
    public static WGPUPipelineLayoutDescriptor createDirect(){
        WGPUPipelineLayoutDescriptor struct = new WGPUPipelineLayoutDescriptor();
        struct.useDirectMemory();
        return struct;
    }


    public DynamicStructRef<WGPUChainedStruct> getNextInChain(){
        return nextInChain;
    }

    public WGPUPipelineLayoutDescriptor setNextInChain(WGPUChainedStruct... x){
        if(x.length == 0 || x[0] == null){
            this.nextInChain.set(JavaWebGPU.createNullPointer());
        } else {
            this.nextInChain.set(x);
        }
        return this;
    }

    public java.lang.String getLabel(){
        return RustCString.fromPointer(label.get());
    }

    public WGPUPipelineLayoutDescriptor setLabel(java.lang.String str){
        this.label.set(RustCString.toPointer(str)); return this;
    }

    public long getBindGroupLayoutCount(){
        return bindGroupLayoutCount.get();
    }

    public WGPUPipelineLayoutDescriptor setBindGroupLayoutCount(long val){
        this.bindGroupLayoutCount.set(val); return this;
    }

    public jnr.ffi.Pointer getBindGroupLayouts(){
        return bindGroupLayouts.get();
    }

    public WGPUPipelineLayoutDescriptor setBindGroupLayouts(jnr.ffi.Pointer val){
        this.bindGroupLayouts.set(val); return this;
    }

}