package com.monstrous.webgpu;

import com.monstrous.utils.JavaWebGPU;
import com.monstrous.utils.CStrPointer;
import com.monstrous.utils.WgpuJavaStruct;
import com.monstrous.utils.RustCString;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUBindGroupEntry extends WgpuJavaStruct {

    private final DynamicStructRef<WGPUChainedStruct> nextInChain = new DynamicStructRef<>(WGPUChainedStruct.class);
    private final Struct.Unsigned32 binding = new Struct.Unsigned32();
    private final Struct.Pointer buffer = new Struct.Pointer();
    private final Struct.Unsigned64 offset = new Struct.Unsigned64();
    private final Struct.Unsigned64 size = new Struct.Unsigned64();
    private final Struct.Pointer sampler = new Struct.Pointer();
    private final Struct.Pointer textureView = new Struct.Pointer();

    private WGPUBindGroupEntry(){}

    @Deprecated
    public WGPUBindGroupEntry(Runtime runtime){
        super(runtime);
    }

	/**
	* Creates this struct on the java heap.
	* In general, this should <b>not</b> be used because these structs
	* cannot be directly passed into native code. 
	*/
    public static WGPUBindGroupEntry createHeap(){
        return new WGPUBindGroupEntry();
    }

	/**
	* Creates this struct in direct memory.
	* This is how most structs should be created (unless, they
	* are members of a nothing struct)
	* 
	* @see WgpuJavaStruct#useDirectMemory
	*/
    public static WGPUBindGroupEntry createDirect(){
        WGPUBindGroupEntry struct = new WGPUBindGroupEntry();
        struct.useDirectMemory();
        return struct;
    }


    public DynamicStructRef<WGPUChainedStruct> getNextInChain(){
        return nextInChain;
    }

    public void setNextInChain(WGPUChainedStruct... x){
        if(x.length == 0 || x[0] == null){
            this.nextInChain.set(JavaWebGPU.createNullPointer());
        } else {
            this.nextInChain.set(x);
        }
    }

    public long getBinding(){
        return binding.get();
    }

    public void setBinding(long x){
        this.binding.set(x);
    }

    public jnr.ffi.Pointer getBuffer(){
        return buffer.get();
    }

    public void setBuffer(jnr.ffi.Pointer x){
        this.buffer.set(x);
    }

    public @jnr.ffi.types.u_int64_t long getOffset(){
        return offset.get();
    }

    public void setOffset(@jnr.ffi.types.u_int64_t long x){
        this.offset.set(x);
    }

    public @jnr.ffi.types.u_int64_t long getSize(){
        return size.get();
    }

    public void setSize(@jnr.ffi.types.u_int64_t long x){
        this.size.set(x);
    }

    public jnr.ffi.Pointer getSampler(){
        return sampler.get();
    }

    public void setSampler(jnr.ffi.Pointer x){
        this.sampler.set(x);
    }

    public jnr.ffi.Pointer getTextureView(){
        return textureView.get();
    }

    public void setTextureView(jnr.ffi.Pointer x){
        this.textureView.set(x);
    }

}