package com.monstrous.webgpu;

import com.monstrous.utils.JavaWebGPU;
import com.monstrous.utils.CStrPointer;
import com.monstrous.utils.WgpuJavaStruct;
import com.monstrous.utils.RustCString;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPURenderBundleEncoderDescriptor extends WgpuJavaStruct {

    private final DynamicStructRef<WGPUChainedStruct> nextInChain = new DynamicStructRef<>(WGPUChainedStruct.class);
    private final @CStrPointer Struct.Pointer label = new Struct.Pointer();
    private final Struct.size_t colorFormatCount = new Struct.size_t();
    private final Struct.Pointer colorFormats = new Struct.Pointer();
    private final Struct.Enum<WGPUTextureFormat> depthStencilFormat = new Struct.Enum<>(WGPUTextureFormat.class);
    private final Struct.Unsigned32 sampleCount = new Struct.Unsigned32();
    private final Struct.Unsigned32 depthReadOnly = new Struct.Unsigned32();
    private final Struct.Unsigned32 stencilReadOnly = new Struct.Unsigned32();

    private WGPURenderBundleEncoderDescriptor(){}

    @Deprecated
    public WGPURenderBundleEncoderDescriptor(Runtime runtime){
        super(runtime);
    }

	/**
	* Creates this struct on the java heap.
	* In general, this should <b>not</b> be used because these structs
	* cannot be directly passed into native code. 
	*/
    public static WGPURenderBundleEncoderDescriptor createHeap(){
        return new WGPURenderBundleEncoderDescriptor();
    }

	/**
	* Creates this struct in direct memory.
	* This is how most structs should be created (unless, they
	* are members of a nothing struct)
	* 
	* @see WgpuJavaStruct#useDirectMemory
	*/
    public static WGPURenderBundleEncoderDescriptor createDirect(){
        WGPURenderBundleEncoderDescriptor struct = new WGPURenderBundleEncoderDescriptor();
        struct.useDirectMemory();
        return struct;
    }


    public DynamicStructRef<WGPUChainedStruct> getNextInChain(){
        return nextInChain;
    }

    public void setNextInChain(WGPUChainedStruct... x){
        if(x.length == 0 || x[0] == null){
            this.nextInChain.set(JavaWebGPU.createNullPointer());
        } else {
            this.nextInChain.set(x);
        }
    }

    public java.lang.String getLabel(){
        return RustCString.fromPointer(label.get());
    }

    public void setLabel(java.lang.String x){
        this.label.set(RustCString.toPointer(x));
    }

    public long getColorFormatCount(){
        return colorFormatCount.get();
    }

    public void setColorFormatCount(long x){
        this.colorFormatCount.set(x);
    }

    public jnr.ffi.Pointer getColorFormats(){
        return colorFormats.get();
    }

    public void setColorFormats(jnr.ffi.Pointer x){
        this.colorFormats.set(x);
    }

    public WGPUTextureFormat getDepthStencilFormat(){
        return depthStencilFormat.get();
    }

    public void setDepthStencilFormat(WGPUTextureFormat x){
        this.depthStencilFormat.set(x);
    }

    public long getSampleCount(){
        return sampleCount.get();
    }

    public void setSampleCount(long x){
        this.sampleCount.set(x);
    }

    public long getDepthReadOnly(){
        return depthReadOnly.get();
    }

    public void setDepthReadOnly(long x){
        this.depthReadOnly.set(x);
    }

    public long getStencilReadOnly(){
        return stencilReadOnly.get();
    }

    public void setStencilReadOnly(long x){
        this.stencilReadOnly.set(x);
    }

}