package com.monstrous.webgpu;

import com.monstrous.utils.JavaWebGPU;
import com.monstrous.utils.CStrPointer;
import com.monstrous.utils.WgpuJavaStruct;
import com.monstrous.utils.RustCString;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUShaderModuleSPIRVDescriptor extends WgpuJavaStruct {

    private final WGPUChainedStruct chain = inner(WGPUChainedStruct.createHeap());
    private final Struct.Unsigned32 codeSize = new Struct.Unsigned32();
    private final Struct.Pointer code = new Struct.Pointer();

    private WGPUShaderModuleSPIRVDescriptor(){}

    @Deprecated
    public WGPUShaderModuleSPIRVDescriptor(Runtime runtime){
        super(runtime);
    }

	/**
	* Creates this struct on the java heap.
	* In general, this should <b>not</b> be used because these structs
	* cannot be directly passed into native code. 
	*/
    public static WGPUShaderModuleSPIRVDescriptor createHeap(){
        return new WGPUShaderModuleSPIRVDescriptor();
    }

	/**
	* Creates this struct in direct memory.
	* This is how most structs should be created (unless, they
	* are members of a nothing struct)
	* 
	* @see WgpuJavaStruct#useDirectMemory
	*/
    public static WGPUShaderModuleSPIRVDescriptor createDirect(){
        WGPUShaderModuleSPIRVDescriptor struct = new WGPUShaderModuleSPIRVDescriptor();
        struct.useDirectMemory();
        return struct;
    }


    public WGPUChainedStruct getChain(){
        return chain;
    }

    public long getCodeSize(){
        return codeSize.get();
    }

    public void setCodeSize(long x){
        this.codeSize.set(x);
    }

    public jnr.ffi.Pointer getCode(){
        return code.get();
    }

    public void setCode(jnr.ffi.Pointer x){
        this.code.set(x);
    }

}