package com.monstrous.webgpu;

import com.monstrous.utils.WgpuJava;
import com.monstrous.utils.CStrPointer;
import com.monstrous.utils.WgpuJavaStruct;
import com.monstrous.utils.RustCString;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPURenderPassDescriptorMaxDrawCount extends WgpuJavaStruct {

    private final WGPUChainedStruct chain = inner(WGPUChainedStruct.createHeap());
    private final Unsigned64 maxDrawCount = new Unsigned64();

    private WGPURenderPassDescriptorMaxDrawCount(){}

    @Deprecated
    public WGPURenderPassDescriptorMaxDrawCount(Runtime runtime){
        super(runtime);
    }

	/**
	* Creates this struct on the java heap.
	* In general, this should <b>not</b> be used because these structs
	* cannot be directly passed into native code. 
	*/
    public static WGPURenderPassDescriptorMaxDrawCount createHeap(){
        return new WGPURenderPassDescriptorMaxDrawCount();
    }

	/**
	* Creates this struct in direct memory.
	* This is how most structs should be created (unless, they
	* are members of a nothing struct)
	* 
	* @see WgpuJavaStruct#useDirectMemory
	*/
    public static WGPURenderPassDescriptorMaxDrawCount createDirect(){
        var struct = new WGPURenderPassDescriptorMaxDrawCount();
        struct.useDirectMemory();
        return struct;
    }


    public WGPUChainedStruct getChain(){
        return chain;
    }

    public @jnr.ffi.types.u_int64_t long getMaxDrawCount(){
        return maxDrawCount.get();
    }

    public void setMaxDrawCount(@jnr.ffi.types.u_int64_t long x){
        this.maxDrawCount.set(x);
    }

}