package com.monstrous.webgpu;

import com.monstrous.utils.JavaWebGPU;
import com.monstrous.utils.CStrPointer;
import com.monstrous.utils.WgpuJavaStruct;
import com.monstrous.utils.RustCString;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;
import org.jetbrains.annotations.Nullable;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WGPUComputePassTimestampWrites extends WgpuJavaStruct {

    private final Struct.Pointer querySet = new Struct.Pointer();
    private final Struct.Unsigned32 beginningOfPassWriteIndex = new Struct.Unsigned32();
    private final Struct.Unsigned32 endOfPassWriteIndex = new Struct.Unsigned32();

    private WGPUComputePassTimestampWrites(){}

    @Deprecated
    public WGPUComputePassTimestampWrites(Runtime runtime){
        super(runtime);
    }

	/**
	* Creates this struct on the java heap.
	* In general, this should <b>not</b> be used because these structs
	* cannot be directly passed into native code. 
	*/
    public static WGPUComputePassTimestampWrites createHeap(){
        return new WGPUComputePassTimestampWrites();
    }

	/**
	* Creates this struct in direct memory.
	* This is how most structs should be created (unless, they
	* are members of a nothing struct)
	* 
	* @see WgpuJavaStruct#useDirectMemory
	*/
    public static WGPUComputePassTimestampWrites createDirect(){
        WGPUComputePassTimestampWrites struct = new WGPUComputePassTimestampWrites();
        struct.useDirectMemory();
        return struct;
    }


    public jnr.ffi.Pointer getQuerySet(){
        return querySet.get();
    }

    public WGPUComputePassTimestampWrites setQuerySet(jnr.ffi.Pointer val){
        this.querySet.set(val); return this;
    }

    public long getBeginningOfPassWriteIndex(){
        return beginningOfPassWriteIndex.get();
    }

    public WGPUComputePassTimestampWrites setBeginningOfPassWriteIndex(long val){
        this.beginningOfPassWriteIndex.set(val); return this;
    }

    public long getEndOfPassWriteIndex(){
        return endOfPassWriteIndex.get();
    }

    public WGPUComputePassTimestampWrites setEndOfPassWriteIndex(long val){
        this.endOfPassWriteIndex.set(val); return this;
    }

}